import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface TestResult {
  category: string;
  testName: string;
  status: 'pass' | 'partial' | 'fail';
  description: string;
  actions: string;
  details: string;
}

const getStatusColor = (status: string): [number, number, number] => {
  switch (status) {
    case 'pass':
      return [34, 197, 94]; // Green
    case 'partial':
      return [234, 179, 8]; // Yellow
    case 'fail':
      return [239, 68, 68]; // Red
    default:
      return [156, 163, 175]; // Gray
  }
};

const getStatusText = (status: string): string => {
  switch (status) {
    case 'pass':
      return '✓ PASS';
    case 'partial':
      return '⚠ PARTIAL';
    case 'fail':
      return '✗ FAIL';
    default:
      return 'UNKNOWN';
  }
};

export const generateSTDReport = (testResults: TestResult[], metadata: any) => {
  const doc = new jsPDF('l', 'mm', 'a4'); // Landscape for more space
  
  // Title
  doc.setFontSize(20);
  doc.setTextColor(0, 0, 0);
  doc.text('Software Testing Document (STD) Report', 148, 15, { align: 'center' });
  
  // Metadata
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 25);
  doc.text(`Test Source: ${metadata.source || 'N/A'}`, 14, 30);
  doc.text(`Total Tests: ${testResults.length}`, 14, 35);
  
  const passCount = testResults.filter(r => r.status === 'pass').length;
  const partialCount = testResults.filter(r => r.status === 'partial').length;
  const failCount = testResults.filter(r => r.status === 'fail').length;
  
  doc.text(`Pass: ${passCount} | Partial: ${partialCount} | Fail: ${failCount}`, 14, 40);
  
  // Summary stats
  doc.setFillColor(240, 240, 240);
  doc.rect(14, 45, 270, 15, 'F');
  doc.setFontSize(12);
  doc.text(`Success Rate: ${((passCount / testResults.length) * 100).toFixed(1)}%`, 20, 53);
  doc.text(`Coverage: ${testResults.length} test scenarios`, 100, 53);
  doc.text(`Status: ${failCount === 0 ? 'READY FOR DEPLOYMENT' : 'REQUIRES ATTENTION'}`, 180, 53);
  
  // Group results by category
  const categories = Array.from(new Set(testResults.map(r => r.category)));
  let yPosition = 65;
  
  categories.forEach((category, index) => {
    const categoryResults = testResults.filter(r => r.category === category);
    
    // Add new page if needed
    if (yPosition > 170) {
      doc.addPage();
      yPosition = 20;
    }
    
    // Category header
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(category.toUpperCase(), 14, yPosition);
    yPosition += 5;
    
    // Create table data
    const tableData = categoryResults.map(result => [
      result.testName,
      getStatusText(result.status),
      result.description,
      result.actions,
      result.details
    ]);
    
    autoTable(doc, {
      startY: yPosition,
      head: [['Test Name', 'Status', 'Description', 'Actions Performed', 'Details']],
      body: tableData,
      theme: 'grid',
      headStyles: { 
        fillColor: [59, 130, 246],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 9
      },
      styles: { 
        fontSize: 8,
        cellPadding: 3
      },
      columnStyles: {
        0: { cellWidth: 50 },
        1: { cellWidth: 20, halign: 'center' },
        2: { cellWidth: 60 },
        3: { cellWidth: 60 },
        4: { cellWidth: 70 }
      },
      didParseCell: function(data) {
        // Color code the status column
        if (data.column.index === 1 && data.section === 'body') {
          const rowIndex = data.row.index;
          const status = categoryResults[rowIndex].status;
          const color = getStatusColor(status);
          data.cell.styles.fillColor = color;
          data.cell.styles.textColor = [255, 255, 255];
          data.cell.styles.fontStyle = 'bold';
        }
      },
      margin: { left: 14, right: 14 }
    });
    
    yPosition = (doc as any).lastAutoTable.finalY + 10;
  });
  
  // Add footer with page numbers
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${pageCount}`,
      148,
      205,
      { align: 'center' }
    );
    doc.text(
      'Generated by Automated QA Testing System',
      148,
      200,
      { align: 'center' }
    );
  }
  
  return doc;
};

export const downloadSTDReport = (testResults: TestResult[], metadata: any) => {
  const doc = generateSTDReport(testResults, metadata);
  const fileName = `STD_Report_${new Date().getTime()}.pdf`;
  doc.save(fileName);
};
